# Generated by Django 2.1.2 on 2018-11-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
