# Generated by Django 2.1.2 on 2018-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0005_auto_20181118_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body1',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='body2',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='body3',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='body4',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
    ]
