# Generated by Django 2.1.2 on 2018-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewApp', '0006_auto_20181118_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='body4',
            field=models.TextField(),
        ),
    ]
